// T'AI HSÜAN CHING — Canon of Supreme Mystery
// 81 Tetragrams (Shou) — Ternary system: Heaven (⚊), Earth (⚋), Man (𝌀)
// Lines built TOP DOWN per Nylan. Each line is 0=Heaven, 1=Earth, 2=Man
// Tetragram number = l1*27 + l2*9 + l3*3 + l4 + 1 (where l1 is top line)

// Three Realms: T'ien (Heaven, 1-27), Jen (Man, 28-54), Ti (Earth, 55-81)

export const THC_TETRAGRAMS = [
  {n:1,name:"Chung",eng:"Centre",lines:[0,0,0,0],realm:"Heaven",explain:"The origin point — pure Heaven in all four positions. This tetragram represents the absolute center, the still point around which all else revolves. You are at the source. Everything begins from here. Center yourself before acting, and act from that centered place."},
  {n:2,name:"Chou",eng:"Full Circle",lines:[0,0,0,1],realm:"Heaven",explain:"The cycle completes itself. What began in the center now traces its full arc. This tetragram speaks of completion, return, and the wholeness that comes from following a process through to its natural conclusion."},
  {n:3,name:"Hsien",eng:"Mired",lines:[0,0,0,2],realm:"Heaven",explain:"Stuck in the mud — movement is blocked or slowed. Like walking through deep earth, progress requires extra effort. Don't panic. Steady, patient effort will free you. The miring is temporary."},
  {n:4,name:"Ko",eng:"Barrier",lines:[0,0,1,0],realm:"Heaven",explain:"An obstacle stands in your way. Unlike being mired (which is gradual entanglement), this is a clear wall. The question is whether to go around it, wait for it to fall, or find a gate. Sometimes barriers exist for a reason — to redirect you."},
  {n:5,name:"Shao",eng:"Keeping Small",lines:[0,0,1,1],realm:"Heaven",explain:"Restraint and modesty. Keep your ambitions small for now — not because you lack ability, but because the time calls for careful, measured steps. Small seeds, well planted, grow into mighty trees."},
  {n:6,name:"Jung",eng:"Contrariety",lines:[0,0,1,2],realm:"Heaven",explain:"Things are working against their own nature — forces are misaligned, purposes are crossed. What should flow is blocked; what should be still is agitated. Recognizing the contrariety is the first step to resolving it."},
  {n:7,name:"Shang",eng:"Ascent",lines:[0,0,2,0],realm:"Heaven",explain:"Rising energy, upward movement. Like smoke rising or a hawk catching a thermal, you are being lifted. The key is to cooperate with this ascending force rather than fighting it or grasping too tightly."},
  {n:8,name:"Kan",eng:"Opposition",lines:[0,0,2,1],realm:"Heaven",explain:"Two forces face each other. This is not necessarily conflict — opposition can be the creative tension between complementary forces. The question is whether this opposition is productive (like the two poles of a magnet) or destructive."},
  {n:9,name:"Ch'a",eng:"Branching Out",lines:[0,0,2,2],realm:"Heaven",explain:"A single trunk divides into many branches. This tetragram speaks of diversification, expansion, and the natural tendency of things to multiply and differentiate. Let your interests and efforts branch naturally."},
  {n:10,name:"Hsiu",eng:"Defectiveness",lines:[0,1,0,0],realm:"Heaven",explain:"Something is flawed or distorted — not catastrophically broken, but subtly off. Like a lens with a slight warp, it changes everything you see through it. Identify the distortion before attempting to correct it."},
  {n:11,name:"Ch'ai",eng:"Divergence",lines:[0,1,0,1],realm:"Heaven",explain:"Paths are separating. What was together is moving apart. This can be natural growth (like children leaving home) or a sign that unity has been lost. Accept the divergence if it's organic; address it if it's premature."},
  {n:12,name:"T'ung",eng:"Youthfulness",lines:[0,1,0,2],realm:"Heaven",explain:"The energy of youth — fresh, eager, unformed. Like a young plant, there is tremendous potential but also vulnerability. Protect and nurture this new growth. Don't burden it with too much expectation too soon."},
  {n:13,name:"Tseng",eng:"Increase",lines:[0,1,1,0],realm:"Heaven",explain:"Growth and expansion in all directions. Resources are multiplying, influence is growing, abundance is increasing. Use this period of increase wisely — channel the growing energy toward worthy ends."},
  {n:14,name:"Jui",eng:"Penetration",lines:[0,1,1,1],realm:"Heaven",explain:"Deep insight, piercing understanding. Like a needle finding the exact pressure point, this tetragram speaks of precision and depth. You can see through to the heart of the matter. Trust your penetrating insight."},
  {n:15,name:"Ta",eng:"Reach",lines:[0,1,1,2],realm:"Heaven",explain:"Your influence extends far. What you do, say, and think has consequences beyond your immediate circle. Be aware of your reach and use it responsibly. Great reach requires great care."},
  {n:16,name:"Chiao",eng:"Contact",lines:[0,1,2,0],realm:"Heaven",explain:"Connection is being made — two things that were separate are coming into contact. This is the moment of meeting, of first touch. Pay attention to the quality of this contact. First impressions matter."},
  {n:17,name:"Chih",eng:"Holding Back",lines:[0,1,2,1],realm:"Heaven",explain:"Restraint — something is being held in check. This may be wise self-control or it may be suppression that will eventually burst. Examine what is being held back and why. Is the dam necessary, or is it blocking natural flow?"},
  {n:18,name:"Hsu",eng:"Waiting",lines:[0,1,2,2],realm:"Heaven",explain:"Active patience. The time for action has not yet arrived, but it will. Prepare yourself, gather your resources, and remain alert. Waiting is not passivity — it is readiness."},
  {n:19,name:"Sui",eng:"Following",lines:[0,2,0,0],realm:"Heaven",explain:"Adapt and follow the current. Sometimes leadership means knowing when to follow — a greater force, a wiser counsel, the flow of events. Surrender your need to direct and let yourself be carried."},
  {n:20,name:"Chin",eng:"Advance",lines:[0,2,0,1],realm:"Heaven",explain:"Move forward. The way is open, the time is right, and hesitation now would be a mistake. Advance with confidence but not recklessness. Each step forward builds momentum for the next."},
  {n:21,name:"Shih",eng:"Release",lines:[0,2,0,2],realm:"Heaven",explain:"Let go. Whatever you've been gripping — a grudge, a fear, an outdated plan — release it now. Freedom comes from letting go, not from holding tighter. The release creates space for something new."},
  {n:22,name:"K'ang",eng:"Resistance",lines:[0,2,1,0],realm:"Heaven",explain:"Something pushes back against you. This resistance is not necessarily your enemy — it may be testing your resolve, strengthening your commitment, or redirecting your path. Examine what the resistance teaches."},
  {n:23,name:"I",eng:"Ease",lines:[0,2,1,1],realm:"Heaven",explain:"Flow and effortlessness. Things move smoothly, without friction or struggle. Enjoy this period of ease, but don't become so comfortable that you stop growing. Ease is a gift, not a permanent state."},
  {n:24,name:"Lo",eng:"Joy",lines:[0,2,1,2],realm:"Heaven",explain:"Genuine happiness and delight. Not mere pleasure but deep, authentic joy that arises from being in harmony with the Tao. Share this joy — it multiplies when given away."},
  {n:25,name:"Cheng",eng:"Contention",lines:[0,2,2,0],realm:"Heaven",explain:"Struggle and competition. Forces are vying for dominance. This tetragram doesn't judge contention as good or bad — sometimes struggle is necessary for growth. But be clear about what you're fighting for."},
  {n:26,name:"Wu",eng:"Endeavor",lines:[0,2,2,1],realm:"Heaven",explain:"Hard work and dedicated effort. Success here comes not from cleverness or luck but from sustained, purposeful labor. Roll up your sleeves. The work itself is the path."},
  {n:27,name:"Shih",eng:"Duties",lines:[0,2,2,2],realm:"Heaven",explain:"Obligations and responsibilities. This tetragram reminds you of what you owe — to others, to your position, to your own integrity. Duty may not be glamorous, but fulfilling it builds the foundation of character."},
  {n:28,name:"Keng",eng:"Change",lines:[1,0,0,0],realm:"Man",explain:"Transformation is underway. The realm of Man begins with change — because humanity's nature is to transform. Whatever has been static is now shifting. Embrace the change rather than clinging to what was."},
  {n:29,name:"Tuan",eng:"Decisiveness",lines:[1,0,0,1],realm:"Man",explain:"The moment of decision. Cut through uncertainty with a clean, clear choice. Indecision is more dangerous now than a wrong decision. Trust your judgment, commit fully, and move."},
  {n:30,name:"I",eng:"Bold Resolution",lines:[1,0,0,2],realm:"Man",explain:"Courageous determination. This goes beyond mere decisiveness — it requires daring. The situation calls for someone willing to take a risk, to stand firm when others waver. Be that person."},
  {n:31,name:"Chuang",eng:"Packing",lines:[1,0,1,0],realm:"Man",explain:"Gathering and organizing resources for a journey or undertaking. Before you can travel, you must pack. Before you can build, you must gather materials. This is the preparation phase — thorough and deliberate."},
  {n:32,name:"Shih",eng:"Legion",lines:[1,0,1,1],realm:"Man",explain:"The assembled multitude — many forces gathered under one banner. Like an army, the strength is in unity and discipline. Whatever force you've gathered (people, resources, arguments), organize it effectively."},
  {n:33,name:"Ch'in",eng:"Closeness",lines:[1,0,1,2],realm:"Man",explain:"Intimacy and proximity. Two things draw near to each other — people, ideas, events. This closeness can be nurturing or suffocating depending on the context. Tend the relationship with care."},
  {n:34,name:"Ch'i",eng:"Kinship",lines:[1,0,2,0],realm:"Man",explain:"Blood ties and deep bonds. The connections that run deeper than choice — family, heritage, the ties that bind us to our origins. Honor these connections even when they're complicated."},
  {n:35,name:"Lien",eng:"Gathering",lines:[1,0,2,1],realm:"Man",explain:"People coming together for a purpose. Unlike Legion (which implies hierarchy), Gathering is more organic — a community forming around shared interest or need. Welcome the gathering."},
  {n:36,name:"Ch'iang",eng:"Strength",lines:[1,0,2,2],realm:"Man",explain:"Raw power and vigor. You have the strength to accomplish what's before you. The question is whether you'll use it wisely. Strength without wisdom is dangerous; strength with wisdom is unstoppable."},
  {n:37,name:"Chieh",eng:"Purity",lines:[1,1,0,0],realm:"Man",explain:"Cleanliness of intention and action. Strip away the unnecessary, the dishonest, the muddied. What remains after purification is the essential truth. Seek purity not as perfection but as clarity."},
  {n:38,name:"Shih",eng:"Fullness",lines:[1,1,0,1],realm:"Man",explain:"Abundance to the point of overflow. Everything is full — your cup, your schedule, your heart. The challenge of fullness is knowing when enough is enough. Don't try to add more to what is already complete."},
  {n:39,name:"Chu",eng:"Residence",lines:[1,1,0,2],realm:"Man",explain:"Home, dwelling, belonging. Where do you live — not just physically but spiritually? This tetragram asks about your true residence, the place where your deepest self feels at home. Tend that inner dwelling."},
  {n:40,name:"Fa",eng:"Law",lines:[1,1,1,0],realm:"Man",explain:"Order, principle, the rule of law. Structure and regulation create the framework within which life can flourish. Without law there is chaos; without flexibility, law becomes tyranny. Find the balance."},
  {n:41,name:"Ying",eng:"Response",lines:[1,1,1,1],realm:"Man",explain:"Pure Earth in all four positions — maximum receptivity. You are being called to respond, not to initiate. Listen deeply. The answer to your question may already be present in the situation itself, waiting for your response."},
  {n:42,name:"Kou",eng:"Going to Meet",lines:[1,1,1,2],realm:"Man",explain:"Moving toward encounter. You are going out to meet something — a person, a destiny, a truth. This is active seeking, not passive waiting. Go forward with open eyes and an open heart."},
  {n:43,name:"Tsao",eng:"Encounters",lines:[1,1,2,0],realm:"Man",explain:"Meetings and intersections. Life brings people and events together in ways that seem random but carry meaning. Pay attention to who and what you encounter today — the universe is speaking through coincidence."},
  {n:44,name:"Tsao",eng:"Stove",lines:[1,1,2,1],realm:"Man",explain:"The place of transformation through heat. Like the alchemist's furnace or the kitchen hearth, the stove represents the transformative power of sustained energy applied to raw materials. What are you cooking?"},
  {n:45,name:"Ta",eng:"Greatness",lines:[1,1,2,2],realm:"Man",explain:"Magnitude and grandeur. Something large is at work — a great person, a great event, a great force. Align yourself with what is truly great, not merely what is big. True greatness serves; false greatness dominates."},
  {n:46,name:"K'uo",eng:"Enlargement",lines:[1,2,0,0],realm:"Man",explain:"Expansion and amplification. What was small grows large; what was quiet grows loud. This is a time of scaling up. Make sure what you're enlarging is worth the expansion."},
  {n:47,name:"Wen",eng:"Pattern",lines:[1,2,0,1],realm:"Man",explain:"The underlying design in things. Like the grain in wood or the veins in a leaf, pattern reveals structure. Look for the pattern in your situation — it will show you both where you've been and where you're heading."},
  {n:48,name:"Li",eng:"Ritual",lines:[1,2,0,2],realm:"Man",explain:"Sacred action performed with intention. Ritual is not empty repetition — it's the deliberate performance of meaningful acts. What rituals sustain you? What sacred practices have you neglected?"},
  {n:49,name:"Fei",eng:"Flight",lines:[1,2,1,0],realm:"Man",explain:"Soaring, escape, transcendence. Whether fleeing danger or rising above limitation, flight represents the human capacity to leave the ground behind. Sometimes the wisest action is to take to the air."},
  {n:50,name:"T'ang",eng:"Vastness",lines:[1,2,1,1],realm:"Man",explain:"Immense scale — the ocean, the sky, the scope of human ambition. This tetragram warns that vastness can overwhelm as easily as it inspires. Navigate the vast space with humility and a clear compass."},
  {n:51,name:"Ch'ang",eng:"Constancy",lines:[1,2,1,2],realm:"Man",explain:"Steadfastness and permanence. In a world of constant change, some things endure. This tetragram points to what is constant in your life — your values, your commitments, your deepest nature. Honor what endures."},
  {n:52,name:"Tu",eng:"Measure",lines:[1,2,2,0],realm:"Man",explain:"Calibration and proportion. Know the measure of things — how much is enough, how far is too far, what fits and what doesn't. The art of measure is the art of wisdom."},
  {n:53,name:"Yung",eng:"Eternity",lines:[1,2,2,1],realm:"Man",explain:"The timeless dimension. Beyond the cycles of day and night, beyond birth and death, something eternal persists. This tetragram connects you to that timeless quality. What in your life touches eternity?"},
  {n:54,name:"K'un",eng:"Unity",lines:[1,2,2,2],realm:"Man",explain:"Perfect oneness — all divisions dissolved. The final tetragram of the realm of Man achieves what humanity always seeks: union with the whole. Drop the illusion of separateness."},
  {n:55,name:"Sun",eng:"Diminishment",lines:[2,0,0,0],realm:"Earth",explain:"The realm of Earth begins with decrease. Resources are contracting, influence is waning, energy is declining. This is natural — like autumn following summer. Use what remains wisely and prepare for the lean times."},
  {n:56,name:"Ch'ien",eng:"Closed Mouth",lines:[2,0,0,1],realm:"Earth",explain:"Silence is called for. Stop talking, stop explaining, stop defending. Close your mouth and open your ears. The wisdom you need right now comes through listening, not speaking."},
  {n:57,name:"Shou",eng:"Guardedness",lines:[2,0,0,2],realm:"Earth",explain:"Protective vigilance. Keep your guard up — not from paranoia but from prudence. Some situations require defensive awareness. Protect what matters without becoming rigid or fearful."},
  {n:58,name:"Lien",eng:"Gathering In",lines:[2,0,1,0],realm:"Earth",explain:"Drawing inward, collecting what has been scattered. Like a harvest, this is the time to bring things home — gather your scattered energies, consolidate your gains, pull your resources close."},
  {n:59,name:"Chi",eng:"Massing",lines:[2,0,1,1],realm:"Earth",explain:"Accumulation of force. Energy builds, pressure mounts, mass gathers. Something is building toward a critical point. Be aware of where the mass is accumulating and what will happen when it reaches the tipping point."},
  {n:60,name:"Chi",eng:"Accumulation",lines:[2,0,1,2],realm:"Earth",explain:"Steady buildup over time. Unlike massing (which has urgency), accumulation is gradual and patient. Small additions, day after day, create great wealth — of resources, knowledge, or character."},
  {n:61,name:"Shih",eng:"Embellishment",lines:[2,0,2,0],realm:"Earth",explain:"Decoration and adornment. Adding beauty to function, art to utility. But the oracle warns: don't mistake embellishment for substance. The decoration should enhance, not replace, what is real."},
  {n:62,name:"Yi",eng:"Doubt",lines:[2,0,2,1],realm:"Earth",explain:"Uncertainty and questioning. Doubt is not weakness — it is the beginning of wisdom. Question your assumptions, examine your beliefs, test your conclusions. The person who never doubts never learns."},
  {n:63,name:"Shih",eng:"Watch",lines:[2,0,2,2],realm:"Earth",explain:"Vigilant observation. Station yourself as a watcher — alert, patient, attentive. Something is approaching that requires your awareness. Watch without judgment, without expectation. Simply observe."},
  {n:64,name:"Ch'en",eng:"Sinking",lines:[2,1,0,0],realm:"Earth",explain:"Downward movement — settling, declining, going under. This may be a healthy sinking (like roots going deep) or an unhealthy one (like drowning). The difference lies in whether the sinking is intentional or uncontrolled."},
  {n:65,name:"Nei",eng:"Inner",lines:[2,1,0,1],realm:"Earth",explain:"The interior world. Turn attention inward — away from the surface of events and toward the inner landscape of thought, feeling, and spirit. The answer you seek is not outside you."},
  {n:66,name:"Ch'u",eng:"Departure",lines:[2,1,0,2],realm:"Earth",explain:"Leaving, going away, the act of separation. Something or someone is departing. This may be necessary — some things must leave to make room for what comes next. Let the departure happen with grace."},
  {n:67,name:"Meng",eng:"Darkening",lines:[2,1,1,0],realm:"Earth",explain:"Light is fading. Clarity gives way to obscurity, understanding to confusion. This is not permanent darkness but a dimming phase. Protect whatever light remains and wait for the dawn."},
  {n:68,name:"Hsiao",eng:"Dimming",lines:[2,1,1,1],realm:"Earth",explain:"A further stage of darkening — the light grows weaker. But even in dimness, shapes can be discerned. Train your eyes to see in low light. Some of the most important truths are visible only in shadow."},
  {n:69,name:"Ch'iung",eng:"Exhaustion",lines:[2,1,1,2],realm:"Earth",explain:"Resources depleted, energy spent, options narrowed. You've reached the end of what this particular path can offer. Rest. Regroup. The exhaustion is telling you that something fundamental needs to change."},
  {n:70,name:"Ko",eng:"Severance",lines:[2,1,2,0],realm:"Earth",explain:"A clean cut — something is being severed. A relationship, a connection, a tie that bound. Severance is painful but sometimes necessary. A clean cut heals faster than a ragged tear."},
  {n:71,name:"Chih",eng:"Stoppage",lines:[2,1,2,1],realm:"Earth",explain:"Complete halt. Everything stops. This isn't mere slowing — it's a full stop. Use this enforced stillness to take stock. What were you doing before the stoppage? Should you resume, or was the universe telling you to change course?"},
  {n:72,name:"Chien",eng:"Hardness",lines:[2,1,2,2],realm:"Earth",explain:"Rigidity, difficulty, toughness. The situation has hardened — what was fluid is now solid, what was flexible is now stiff. Hardness can mean strength or brittleness. Know which kind you're dealing with."},
  {n:73,name:"Ch'eng",eng:"Completion",lines:[2,2,0,0],realm:"Earth",explain:"The work is done. A cycle closes, a task finishes, a process reaches its end. Honor the completion before rushing to begin something new. Every ending deserves its moment of recognition."},
  {n:74,name:"Pi",eng:"Closure",lines:[2,2,0,1],realm:"Earth",explain:"Shutting down, closing off, sealing up. Doors are closing — some by your choice, some by circumstance. Accept the closure. What is meant for you will find an open door."},
  {n:75,name:"Pai",eng:"Failure",lines:[2,2,0,2],realm:"Earth",explain:"Things have not worked out. This is not a judgment but a statement of fact. Failure is one of the great teachers. What did this failure show you? What will you do differently? The only true failure is refusing to learn."},
  {n:76,name:"Chu",eng:"Aggravation",lines:[2,2,1,0],realm:"Earth",explain:"Things are getting worse before they get better. Irritation compounds, problems multiply, patience frays. This is the dark before the dawn — but you must endure the aggravation before the relief comes."},
  {n:77,name:"Shun",eng:"Compliance",lines:[2,2,1,1],realm:"Earth",explain:"Yielding and going along. Sometimes compliance is wisdom — fighting every battle leads to exhaustion. Sometimes compliance is cowardice. Know the difference. Comply with what serves the greater good; resist what corrupts it."},
  {n:78,name:"Lin",eng:"On the Verge",lines:[2,2,1,2],realm:"Earth",explain:"The edge of something — about to happen, almost there, on the brink. This tetragram carries tremendous potential energy. You're standing at the precipice. What happens next depends on your next step."},
  {n:79,name:"Nan",eng:"Difficulties",lines:[2,2,2,0],realm:"Earth",explain:"Hard times, obstacles, suffering. The realm of Earth teaches through difficulty. These are not punishments but lessons. The difficulties are shaping you. How you respond to them defines who you become."},
  {n:80,name:"Ch'in",eng:"Laboring",lines:[2,2,2,1],realm:"Earth",explain:"Hard, grinding work — the kind that wears you down but also builds you up. There is no shortcut through this tetragram. The only way is through sustained effort. The labor will end, and what you've built will stand."},
  {n:81,name:"Yang",eng:"Fostering",lines:[2,2,2,2],realm:"Earth",explain:"Pure Man in all four positions — maximum humanity. The final tetragram represents the deepest human capacity: to nurture, cultivate, and foster growth in others. You are being called to be a gardener of souls, a fosterer of potential. This is the highest human calling."},
];

// Coin method for THC: throw 2 coins twice (re-throw if both tails)
// Total heads: 2=Heaven(solid), 3=Earth(broken once), 4=Man(broken twice)
export function throwTHCLine() {
  const throwPair = () => {
    let a, b;
    do {
      a = Math.random() < 0.5 ? 1 : 0;
      b = Math.random() < 0.5 ? 1 : 0;
    } while (a === 0 && b === 0); // re-throw if both tails
    return a + b; // 1 or 2 heads from this pair
  };
  const total = throwPair() + throwPair(); // 2, 3, or 4
  // 2 heads = Heaven (0), 3 = Earth (1), 4 = Man (2)
  return { value: total - 2, sum: total, label: total === 2 ? "HEAVEN ⚊" : total === 3 ? "EARTH ⚋" : "MAN 𝌀" };
}

export function lookupTHC(lines) {
  // lines[0] = top, lines[3] = bottom (Nylan: top-down)
  const idx = lines[0] * 27 + lines[1] * 9 + lines[2] * 3 + lines[3];
  return THC_TETRAGRAMS[idx] || THC_TETRAGRAMS[0];
}
